[terminal]
shell = "C:\\Windows\\System32\\wsl.exe -d debian"


[window]
opacity = 0.7
startup_mode = "Fullscreen"
# startup_mode = "Maximized"

[keyboard]

bindings = [

	{key = "q", mods = "Control", action = "Quit"}





]

